# Prometheus配置文件 - 中国大陆开发环境
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'go-aigateway-cn-dev'
    region: 'china'

rule_files:
  # - "rules/*.yml"

scrape_configs:
  # AI网关主服务监控
  - job_name: 'go-aigateway'
    static_configs:
      - targets: ['go-aigateway:9090']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Python模型服务监控
  - job_name: 'python-model'
    static_configs:
      - targets: ['python-model-cn:5000']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-cn:6379']
    scrape_interval: 30s

  # PostgreSQL监控
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-cn:5432']
    scrape_interval: 30s

  # Prometheus自监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (如果有的话)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

# 告警配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# 数据保留
storage:
  tsdb:
    retention.time: 15d
    retention.size: 10GB
