version: '3.8'

services:
  # AI Gateway 主服务 (纯本地部署)
  ai-gateway:
    build: .
    ports:
      - "8080:8080"
    environment:
      # 基础配置
      - PORT=8080
      - GIN_MODE=release
      - LOG_LEVEL=info
      - LOG_FORMAT=text
      
      # 本地认证配置
      - ENABLE_LOCAL_AUTH=true
      - JWT_SECRET=local-deployment-super-secure-jwt-secret-key-at-least-32-characters
      - TOKEN_EXPIRATION=24h
      - REQUIRE_HTTPS=false
      - API_KEY_PREFIX=local_
      
      # 本地模型配置
      - LOCAL_MODEL_ENABLED=true
      - LOCAL_MODEL_HOST=localhost
      - LOCAL_MODEL_PORT=5000
      - LOCAL_MODEL_TYPE=chat
      - LOCAL_MODEL_SIZE=small
      - LOCAL_MODEL_MAX_TOKENS=1024
      - LOCAL_MODEL_TEMPERATURE=0.7
      - LOCAL_MODEL_TIMEOUT=30s
      - PYTHON_PATH=python
      - MODEL_PATH=/app/python/model
      
      # CORS 配置
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:5173
      
      # 限流配置
      - RATE_LIMIT_REQUESTS_PER_MINUTE=120
      
      # 健康检查
      - HEALTH_CHECK_ENABLED=true
      
      # 禁用所有云服务和第三方依赖
      - CLOUD_INTEGRATION_ENABLED=false
      - SERVICE_DISCOVERY_ENABLED=false
      - PROTOCOL_CONVERSION_ENABLED=false
      - RAM_AUTH_ENABLED=false
      - REDIS_ENABLED=false
      - AUTO_SCALING_ENABLED=false
      - MONITORING_ENABLED=true
      - MONITORING_ALERTS_ENABLED=false
      
    volumes:
      - ./python:/app/python
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - ai-gateway-local

  # 可选: Redis (如果需要缓存功能)
  redis:
    image: redis:7-alpine
    container_name: ai-gateway-redis-local
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3
    networks:
      - ai-gateway-local
    profiles:
      - with-redis

volumes:
  redis_data:

networks:
  ai-gateway-local:
    driver: bridge
