apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-gateway
  labels:
    app: ai-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-gateway
  template:
    metadata:
      labels:
        app: ai-gateway
    spec:
      containers:
        - name: ai-gateway
          image: ai-gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: GIN_MODE
              value: "release"
            - name: TARGET_API_URL
              value: "https://dashscope.aliyuncs.com/compatible-mode/v1"
            - name: TARGET_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-gateway-secret
                  key: target-api-key
            - name: GATEWAY_API_KEYS
              valueFrom:
                secretKeyRef:
                  name: ai-gateway-secret
                  key: gateway-api-keys
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_FORMAT
              value: "json"
            - name: RATE_LIMIT_REQUESTS_PER_MINUTE
              value: "60"
            - name: HEALTH_CHECK_ENABLED
              value: "true"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: ai-gateway-service
spec:
  selector:
    app: ai-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: Secret
metadata:
  name: ai-gateway-secret
type: Opaque
data:
  target-api-key: eW91ci1kYXNoc2NvcGUtYXBpLWtleS1oZXJl # base64 encoded
  gateway-api-keys: c2stZ2F0ZXdheS1rZXkx # base64 encoded
