global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "aigateway-backend"
    static_configs:
      - targets: ["backend:8080"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "aigateway-python"
    static_configs:
      - targets: ["python-models:8081"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:9187"]
    scrape_interval: 10s

  - job_name: "redis"
    static_configs:
      - targets: ["redis:9121"]
    scrape_interval: 10s

  - job_name: "consul"
    static_configs:
      - targets: ["consul:8500"]
    scrape_interval: 10s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
