# Air 热重载配置文件 (Go后端开发优化)
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # 编译输出的二进制文件名
  bin = "./tmp/main"
  
  # 编译命令
  cmd = "go build -o ./tmp/main ."
  
  # 延迟重启时间，避免频繁重启
  delay = 1000
  
  # 监听的文件扩展名
  include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml", "toml", "json"]
  
  # 排除的文件扩展名
  exclude_ext = ["tmp", "log", "vendor"]
  
  # 排除的目录
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "node_modules", "frontend", "deployment", ".git"]
  
  # 排除的文件
  exclude_file = []
  
  # 排除的正则表达式
  exclude_regex = ["_test\\.go"]
  
  # 排除未变更的文件
  exclude_unchanged = false
  
  # 跟随符号链接
  follow_symlink = false
  
  # 启用颜色输出
  full_bin = ""
  
  # 自定义构建参数
  args_bin = []
  
  # 预命令（构建前执行）
  pre_cmd = []
  
  # 后命令（构建后执行）
  post_cmd = []
  
  # 发送中断信号
  send_interrupt = false
  
  # 强制杀死进程
  kill_delay = "0s"

[log]
  # 显示时间
  time = true
  
  # 主颜色
  main_only = false

[color]
  # 自定义颜色
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  # 清屏
  clean_on_exit = false
