# Prometheus 监控配置
# ============================================
# 全局配置
# ============================================
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: "ai-gateway-prod"
    environment: "production"

# ============================================
# 规则文件
# ============================================
rule_files:
  - "/etc/prometheus/rules/*.yml"

# ============================================
# 抓取配置
# ============================================
scrape_configs:
  # Prometheus 自身监控
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 5s
    metrics_path: "/metrics"

  # Go 后端服务监控
  - job_name: "ai-gateway-backend"
    static_configs:
      - targets: ["go-backend:9091"]
    scrape_interval: 10s
    metrics_path: "/metrics"
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "ai-gateway-backend"

  # Python 模型服务监控
  - job_name: "ai-gateway-models"
    static_configs:
      - targets: ["python-models:5000"]
    scrape_interval: 30s
    metrics_path: "/metrics"
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "ai-gateway-models"

  # Redis 监控
  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    scrape_interval: 30s
    metrics_path: "/metrics"

  # PostgreSQL 监控
  - job_name: "postgresql"
    static_configs:
      - targets: ["postgres:5432"]
    scrape_interval: 30s
    metrics_path: "/metrics"

  # Consul 服务发现监控
  - job_name: "consul"
    static_configs:
      - targets: ["consul:8500"]
    scrape_interval: 30s
    metrics_path: "/v1/agent/metrics"
    params:
      format: ["prometheus"]

  # 动态服务发现 (通过 Consul)
  - job_name: "consul-services"
    consul_sd_configs:
      - server: "consul:8500"
        datacenter: "dc1"
    relabel_configs:
      - source_labels: [__meta_consul_service]
        target_label: job
      - source_labels: [__meta_consul_service_id]
        target_label: instance
      - source_labels: [__meta_consul_tags]
        target_label: tags

# ============================================
# 告警管理器配置
# ============================================
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
# ============================================
# 远程写入配置 (可选)
# ============================================
# remote_write:
#   - url: "https://your-remote-storage/api/v1/write"
#     queue_config:
#       max_samples_per_send: 1000
#       max_shards: 200
#       capacity: 2500
