apiVersion: apps/v1
kind: Deployment
metadata:
  name: aigateway-backend
  labels:
    app: aigateway-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aigateway-backend
  template:
    metadata:
      labels:
        app: aigateway-backend
    spec:
      containers:
        - name: backend
          image: aigateway/backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: ENV
              value: "production"
            - name: POSTGRES_HOST
              value: "postgres-service"
            - name: REDIS_HOST
              value: "redis-service"
            - name: CONSUL_ADDR
              value: "consul-service:8500"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: aigateway-backend-service
spec:
  selector:
    app: aigateway-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aigateway-frontend
  labels:
    app: aigateway-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aigateway-frontend
  template:
    metadata:
      labels:
        app: aigateway-frontend
    spec:
      containers:
        - name: frontend
          image: aigateway/frontend:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: aigateway-frontend-service
spec:
  selector:
    app: aigateway-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aigateway-python
  labels:
    app: aigateway-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aigateway-python
  template:
    metadata:
      labels:
        app: aigateway-python
    spec:
      containers:
        - name: python-models
          image: aigateway/python:latest
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: aigateway-python-service
spec:
  selector:
    app: aigateway-python
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
