# 第三方AI服务配置
# 支持多种AI服务提供商的配置

# ==========================================
# 通义千问配置
# ==========================================
tongyi:
  enabled: true
  base_url: "https://dashscope.aliyuncs.com/api/v1"
  api_key: "${TONGYI_API_KEY}"
  models:
    - name: "qwen-turbo"
      max_tokens: 8192
      supports_streaming: true
      rate_limit: 100
    - name: "qwen-plus"
      max_tokens: 32768
      supports_streaming: true
      rate_limit: 50
    - name: "qwen-max"
      max_tokens: 8192
      supports_streaming: true
      rate_limit: 20
  timeout: 30s
  retry_count: 3
  retry_delay: 1s

# ==========================================
# OpenAI配置
# ==========================================
openai:
  enabled: true
  base_url: "https://api.openai.com/v1"
  api_key: "${OPENAI_API_KEY}"
  organization: "${OPENAI_ORG_ID}"
  models:
    - name: "gpt-3.5-turbo"
      max_tokens: 4096
      supports_streaming: true
      rate_limit: 200
    - name: "gpt-4"
      max_tokens: 8192
      supports_streaming: true
      rate_limit: 50
    - name: "gpt-4-turbo"
      max_tokens: 128000
      supports_streaming: true
      rate_limit: 100
  timeout: 60s
  retry_count: 3
  retry_delay: 2s

# ==========================================
# 百度文心一言配置
# ==========================================
wenxin:
  enabled: true
  base_url: "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop"
  api_key: "${WENXIN_API_KEY}"
  secret_key: "${WENXIN_SECRET_KEY}"
  models:
    - name: "ernie-bot"
      max_tokens: 2048
      supports_streaming: true
      rate_limit: 100
    - name: "ernie-bot-turbo"
      max_tokens: 7168
      supports_streaming: true
      rate_limit: 200
    - name: "ernie-bot-4"
      max_tokens: 8192
      supports_streaming: true
      rate_limit: 50
  timeout: 30s
  retry_count: 3
  retry_delay: 1s

# ==========================================
# 智谱AI配置
# ==========================================
zhipu:
  enabled: true
  base_url: "https://open.bigmodel.cn/api/paas/v4"
  api_key: "${ZHIPU_API_KEY}"
  models:
    - name: "glm-4"
      max_tokens: 8192
      supports_streaming: true
      rate_limit: 100
    - name: "glm-3-turbo"
      max_tokens: 32768
      supports_streaming: true
      rate_limit: 200
  timeout: 30s
  retry_count: 3
  retry_delay: 1s

# ==========================================
# 腾讯混元配置
# ==========================================
hunyuan:
  enabled: true
  base_url: "https://hunyuan.tencentcloudapi.com"
  secret_id: "${HUNYUAN_SECRET_ID}"
  secret_key: "${HUNYUAN_SECRET_KEY}"
  region: "ap-beijing"
  models:
    - name: "hunyuan-lite"
      max_tokens: 4096
      supports_streaming: true
      rate_limit: 200
    - name: "hunyuan-standard"
      max_tokens: 8192
      supports_streaming: true
      rate_limit: 100
    - name: "hunyuan-pro"
      max_tokens: 32768
      supports_streaming: true
      rate_limit: 50
  timeout: 30s
  retry_count: 3
  retry_delay: 1s

# ==========================================
# 月之暗面Kimi配置
# ==========================================
moonshot:
  enabled: true
  base_url: "https://api.moonshot.cn/v1"
  api_key: "${MOONSHOT_API_KEY}"
  models:
    - name: "moonshot-v1-8k"
      max_tokens: 8192
      supports_streaming: true
      rate_limit: 100
    - name: "moonshot-v1-32k"
      max_tokens: 32768
      supports_streaming: true
      rate_limit: 50
    - name: "moonshot-v1-128k"
      max_tokens: 131072
      supports_streaming: true
      rate_limit: 20
  timeout: 60s
  retry_count: 3
  retry_delay: 2s

# ==========================================
# 全局配置
# ==========================================
global:
  # 默认超时时间
  default_timeout: 30s

  # 默认重试配置
  default_retry_count: 3
  default_retry_delay: 1s

  # 连接池配置
  max_idle_conns: 100
  max_idle_conns_per_host: 10
  idle_conn_timeout: 90s

  # 请求限制
  max_request_size: 10MB
  max_response_size: 50MB

  # 缓存配置
  cache_enabled: true
  cache_ttl: 300s
  cache_max_size: 1000

  # 监控配置
  metrics_enabled: true
  tracing_enabled: true

  # 负载均衡策略
  load_balance_strategy: "round_robin" # round_robin, random, least_connections

  # 健康检查
  health_check_enabled: true
  health_check_interval: 30s
  health_check_timeout: 5s

  # 安全配置
  rate_limit_enabled: true
  auth_required: true
  tls_verify: true
